import React from 'react';
import { Container } from '@mui/material';
import UserList from '../components/UserList';

const mockUsers = [
    {"id":1,"name":"Mariska Dedmam"},
    {"id":2,"name":"Zacharie Lugden"},
    {"id":3,"name":"Kerri Sullly"},
    {"id":4,"name":"Gavra Ross"},
    {"id":5,"name":"Karney Munby"},
    {"id":6,"name":"Reyna Skentelbury"},
    {"id":7,"name":"Ammamaria Giraths"},
    {"id":8,"name":"Bron Brierton"},
    {"id":9,"name":"Elia Mosdell"},
    {"id":10,"name":"Urbanus Beckworth"},
    {"id":11,"name":"Alaster Kubiczek"},
    {"id":12,"name":"Chevalier Brouard"},
    {"id":13,"name":"Vittorio MacKay"},
    {"id":14,"name":"Stephan Lemerle"},
    {"id":15,"name":"Rudiger Clapshaw"},
    {"id":16,"name":"Lavinie Ordish"},
    {"id":17,"name":"Jori Inkpen"},
    {"id":18,"name":"Asia Kunzel"},
    {"id":19,"name":"Krispin Bayly"},
    {"id":20,"name":"Thomasina Deeth"},
    {"id":21,"name":"Sheena Matyukon"},
    {"id":22,"name":"Burnard Cawson"},
    {"id":23,"name":"Briant Kluss"},
    {"id":24,"name":"Moselle Biasotti"},
    {"id":25,"name":"Meridel Harvie"},
    {"id":26,"name":"Roda Gunson"},
    {"id":27,"name":"Wolf Abbs"},
    {"id":28,"name":"Josepha Fairbanks"},
    {"id":29,"name":"Shannan Lathan"},
    {"id":30,"name":"Tyrus Eliesco"},
    {"id":31,"name":"Christina Dibbert"},
    {"id":32,"name":"Ragnar Goggen"},
    {"id":33,"name":"Ursuline Creeber"},
    {"id":34,"name":"Brand Strutton"},
    {"id":35,"name":"Ula Guitt"},
    {"id":36,"name":"Kirby Sterling"},
    {"id":37,"name":"Christalle Bowdrey"},
    {"id":38,"name":"Cati Spinas"},
    {"id":39,"name":"Tremain Grichukhin"},
    {"id":40,"name":"Wash Ewdale"},
    {"id":41,"name":"Star Sumnall"},
    {"id":42,"name":"Laurent Ridout"},
    {"id":43,"name":"Clark Matlock"},
    {"id":44,"name":"Veronike Bythway"},
    {"id":45,"name":"Teodora Blazi"},
    {"id":46,"name":"Valina Dewdeny"},
    {"id":47,"name":"Franni MacDwyer"},
    {"id":48,"name":"Tish Manders"},
    {"id":49,"name":"Jory Cleminson"},
    {"id":50,"name":"Cosimo Ruusa"},
    {"id":51,"name":"Daune Opy"},
    {"id":52,"name":"Verena Burdfield"},
    {"id":53,"name":"Minnnie Bullard"},
    {"id":54,"name":"Minerva Doberer"},
    {"id":55,"name":"Burl Minucci"},
    {"id":56,"name":"Lauryn Gartell"},
    {"id":57,"name":"Ulick Farthing"},
    {"id":58,"name":"Dina MacCarlich"},
    {"id":59,"name":"Vincenty Speddin"},
    {"id":60,"name":"Sarena Tuley"},
    {"id":61,"name":"Stanwood Pund"},
    {"id":62,"name":"Dyan Krolle"},
    {"id":63,"name":"Nanice Larby"},
    {"id":64,"name":"Saloma Dallaghan"},
    {"id":65,"name":"Emmott Coales"},
    {"id":66,"name":"Demott Yannoni"},
    {"id":67,"name":"Cindelyn Haig"},
    {"id":68,"name":"Kathleen Leyborne"},
    {"id":69,"name":"Gwendolyn Creevy"},
    {"id":70,"name":"Karoly Hawkes"},
    {"id":71,"name":"Forster Sultana"},
    {"id":72,"name":"Robbie Graffin"},
    {"id":73,"name":"Paige Ouslem"},
    {"id":74,"name":"Keefer Springer"},
    {"id":75,"name":"Felecia Liffey"},
    {"id":76,"name":"Emmalee Gorling"},
    {"id":77,"name":"Jaynell Walczynski"},
    {"id":78,"name":"Ingmar Rucklidge"},
    {"id":79,"name":"Sybille Daddow"},
    {"id":80,"name":"Shantee Guinness"},
    {"id":81,"name":"Artie Iannitti"},
    {"id":82,"name":"Georgia Audley"},
    {"id":83,"name":"Eda O' Shea"},
    {"id":84,"name":"Giffie Ewens"},
    {"id":85,"name":"Galven Garbutt"},
    {"id":86,"name":"Mile Arlt"},
    {"id":87,"name":"Cynthie Laurenzi"},
    {"id":88,"name":"Fenelia Espinet"},
    {"id":89,"name":"Melisse Boumphrey"},
    {"id":90,"name":"Basia Sweetzer"},
    {"id":91,"name":"Idaline Dunguy"},
    {"id":92,"name":"Rawley Heggs"},
    {"id":93,"name":"Zack Cady"},
    {"id":94,"name":"Nicolai Cork"},
    {"id":95,"name":"Gilberta Gervaise"},
    {"id":96,"name":"Sanson Youle"},
    {"id":97,"name":"Rhoda Mickan"},
    {"id":98,"name":"Leigh Straine"},
    {"id":99,"name":"Valeda Mintrim"},
    {"id":100,"name":"Winfield Polk"}
];

const Users: React.FC = () => {
  return (
    <Container  maxWidth="md" sx={{ marginTop: 4 }}>
      <h1>Users</h1>
      <UserList users={mockUsers} />
    </Container>
  );
};

export default Users;
